#!/usr/local/bin/bash

term=$1

if grep -v '\.' <<<$term > /dev/null && [[ -f ~/tmp/collection/objects/$((term/1000))/$term.json ]]; then
  # $term is an existing object's id
  id=$term
else
  # ask sphinx
  result=$(curl --silent "https://collections.artsmia.org/search_controller.php" -d 'page=search' --data-urlencode "query=$term");
  if egrep -q "no result" <<<$result; then
    echo $term -- no match;
    exit 1
  else
    id=$(jq -r '.message[0]' <<<$result | cut -d'_' -f1);
  fi
fi

>&2 echo $id
jq '.' < ~/tmp/collection/objects/$((id/1000))/$id.json
