#!/usr/local/bin/bash

[[ ! -z $MIA_COLLECTION ]] && collection=$MIA_COLLECTION || collection=~/tmp/collection

if [[ -z "$@" || ! -d "$collection" ]]; then
  echo "USAGE: mia <terms>"
  echo "  terms can be object ids or other things."
  echo "  if other, you need an internet connection to run a search against our collections server."
  echo "  quote terms with more than one word: \`mia 'three bathers 1907'\`"
  echo
  exit 1
fi

for term in "$@"; do
  if egrep '^[0-9]+$' <<<$term > /dev/null && \
    [[ "$$(ls $collection*/objects/$((term/1000))/$term.json | wc -l)" != "0"  ]]; then
    # $term is an existing object's id
    ids=$term
  else
    # ask ES
    result=$(curl --silent "http://search.staging.artsmia.org/$term");
    if egrep -q '"total": 0,' <<<$result; then
      >&2 echo $term -- no match;
      continue
    else
      ids=$(jq -r '.hits.hits[]._id' <<<$result)
    fi
  fi

  for id in $ids; do
    file=$collection*/objects/$((id/1000))/$id.json
    >&2 echo $id -- $file
    jq '.' < $file | sed 's|http://api.artsmia.org/objects/||'
  done
  >&2 echo
done
